// Mocks generated by Mockito 5.4.4 from annotations
// in my_practice_bloc/test/profile/remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_practice_bloc/features/dashboard/data/datasources/profile_remote_datasource.dart'
    as _i3;
import 'package:my_practice_bloc/features/dashboard/data/models/profile_model.dart'
    as _i2;
import 'package:my_practice_bloc/features/dashboard/domain/usecases/dashboard_params.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileModel_0 extends _i1.SmartFake implements _i2.ProfileModel {
  _FakeProfileModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDatasource extends _i1.Mock
    implements _i3.ProfileRemoteDatasource {
  @override
  _i4.Future<_i2.ProfileModel> getUser(_i5.DashboardParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [params],
        ),
        returnValue: _i4.Future<_i2.ProfileModel>.value(_FakeProfileModel_0(
          this,
          Invocation.method(
            #getUser,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ProfileModel>.value(_FakeProfileModel_0(
          this,
          Invocation.method(
            #getUser,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.ProfileModel>);
}
